apiVersion: v1
kind: ConfigMap
metadata:
  name: isik-hapi-pgadmin-config
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "PostgreSQL DB",
            "Group": "Servers",
            "Port": 5432,
            "Username": "postgres",
            "Host": "isik-hapi-db.cfayfrqrsmtj.eu-central-1.rds.amazonaws.com",
            "SSLMode": "prefer",
            "MaintenanceDB": "isik-hapi-db"
          }
        }
    }
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: isik-hapi-pgadmin
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - uid=5050
parameters:
  type: gp2
  fsType: ext4

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: isik-hapi-pgadmin
spec:
  serviceName: isik-hapi-pgadmin-service
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 5050
      containers:
        - name: isik-hapi-pgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: Always
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: beatriz.correia@incentergy.de
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: isik-hapi-pgadmin
                  key: isik-hapi-pgadmin-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: isik-hapi-pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
#            - name: pgadmin-data
#              mountPath: /var/lib/pgadmin
      volumes:
        - name: isik-hapi-pgadmin-config
          configMap:
            name: isik-hapi-pgadmin-config
#        - name: pgadmin-data
#          persistentVolumeClaim:
#            claimName: pgadmin-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isik-hapi-pgadmin-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: isik-hapi-pgadmin
  resources:
    requests:
      storage: 3Gi

---
kind: Service
apiVersion: v1
metadata:
  name: isik-hapi-pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isik-hapi-pgadmin
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - isik-hapi-pgadmin.med-united.health
      secretName: isik-hapi-pgadmin-tls
  rules:
    - host: isik-hapi-pgadmin.med-united.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: isik-hapi-pgadmin
                port:
                  number: 80
